logging:
  level:
    com:
      zhongz:
        rental:
          mapper: debug
mybatis:
  configLocation: classpath:mapper/mybatis-config.xml
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  typeAliasesPackage: com.zhongz.rental
server:
  port: 8083
  servlet:
    context-path: /zhongz-rental-service
spring:
  application:
    name: zhongz-rental-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall,slf4j
    initialSize: 5
    logSlowSql: true
    maxActive: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    validationQuery: SELECT 1 FROM DUAL
    #测试环境
    url: jdbc:mysql://127.0.0.1:3306/zhongz?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: zhongz
    password: Zhongz@database#2019
    #公司环境
#    url: jdbc:mysql://172.16.175.22:3306/zhongzhu?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
#    username: zhongzhu
#    password: 123456
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 1000MB
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/,file:${web.upload-path},file:static/
swagger:
  basepackage: com.zhongz.rental
  contact: www.china-dt.com/
  description: 中筑-知邸公寓API
  termsOfServiceUrl: http://www.china-dt.com/
  title: 中筑-知邸公寓API
  version: 1.0.0
whitelist:
  urls:
    - /system/zhongzUser/login
    - /system/zhongzValidateCode/get
    - /system/zhongzHouse/list
    - /system/zhongzHouse/listRentType
    - /system/zhongzHouse/single
    - /system/zhongzDirectionType/list
    - /system/zhongzEstate/list
    - /system/zhongzEstate/single
    - /system/zhongzEvent/list
    - /system/zhongzEvent/single
    - /system/zhongzHotTag/list
    - /system/zhongzMediaFile/listHouseFiles
    - /system/zhongzRentType/list
    - /system/zhongzRoom/listByHouseId
    - /system/zhongzRoom/single
    - /system/zhongzStructureType/list
    - /system/zhongzComment/add
    - /system/zhongzManager/info
    - /system/zhongzRequestServiceType/listRepairType
    - /system/zhongzRequestServiceType/listCleaningType
    - /v2/api-docs
    - /configuration/ui
    - /swagger-resources/**
    - /configuration/security
    - /swagger-ui.html
    - /webjars/**
    - /images/**
    - /videos/**
    - /files/**
    - /ajax/**
    - /css/**
    - /file/**
    - /fonts/**
    - /img/**
    - /js/**
    - /ruoyi/**
    - /error